# Generated by Django 4.2.11 on 2025-01-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('artist', models.CharField(max_length=1024)),
                ('bpm', models.IntegerField()),
                ('category', models.CharField(max_length=1024)),
                ('vesion', models.CharField(max_length=1024)),
                ('chart_designer', models.CharField(max_length=1024)),
                ('basic_difficulty', models.FloatField()),
                ('advanced_difficulty', models.FloatField()),
                ('expert_difficulty', models.FloatField()),
                ('master_difficulty', models.FloatField()),
                ('remaster_difficulty', models.FloatField()),
            ],
        ),
    ]
