# Generated by Django 4.2.11 on 2025-01-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='MusicModel',
        ),
    ]
